# Generated by Django 6.0.2 on 2026-02-08 06:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price for sale (optional)', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_auctions', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auctions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bids',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'end_time'], name='auctions_status_3d6271_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['owner'], name='auctions_owner_i_acb51e_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-amount'], name='bids_auction_5cbac0_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder'], name='bids_bidder__a777a2_idx'),
        ),
    ]
